#!/usr/bin/env python3
"""Generate the reliability-mode demo lattice and its analytic ground truth.

Writes, next to this script:

* ``reliability_demo.dat``   — a 2.8 m proton channel: three cells of
  (steerer, solenoid, RF gap, aperture, BPM) plus a fourth gap and a
  carbon stripper foil.  Every element type the reliability legs touch
  is present (cavities to fail, solenoids to fail and misalign, steerers
  with ``ADJUST_STEERER`` cards for orbit correction, BPM markers,
  apertures for losses, a foil for leg D).  20 MeV injection keeps the
  gaps' RF defocusing (f ~ -12 m) well below the solenoid focusing
  (f ~ +5 m): the 0.75 m cell is stable at ~17 deg per period.
* ``reliability_demo.lgproj`` — the beam (proton 20 MeV, 162.5 MHz, 0 mA,
  1 % duty) so a campaign can be started from the project file.
* ``circuits.json``          — the circuit map (cryomodules, RF stations,
  sections, landmarks) the reliability engine reads.
* ``truth.json``             — analytic answers computed HERE with the
  script's own kinematics (no HELIX import), against which the built-in
  self-test compares:

  - re-phased cavity-OFF energy deficits  = V cos(phi_s) (thin gap, T = 1);
  - frozen-phase cavity-OFF deficits: with gap i off the reference is
    slower, every downstream drift advances the RF clock by
    360 L / (beta lambda) more than on the design pass, and gap j then
    delivers V_j cos(phi_j + dphi_j) — the chain is integrated below;
  - the design-pass clock phase at every gap entrance (the pins);
  - foil mean loss (minimum-ionising constant x thickness) and the
    Highland scattering angle at the foil energy;
  - availability closed forms (single block, series, parallel, k-of-n);
  - deck-design facts: the top-ranked single cavity fault and the k = 1
    nearest-neighbour compensators of the last gap.

Usage::

    python3 examples/reliability_demo/make_reliability_demo.py
"""
from __future__ import annotations

import json
import math
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent

# --------------------------------------------------------------------------
# Physical constants (CODATA 2018 — the same values HELIX carries in
# linac_gen/core/constants.py; copied, not imported).
# --------------------------------------------------------------------------
M_PROTON_MEV = 938.27208816
C_LIGHT = 299792458.0

FREQ_MHZ = 162.5
W_INJ_MEV = 20.0
LAMBDA_MM = C_LIGHT / (FREQ_MHZ * 1e6) * 1000.0

# Gap voltages (V, TraceWin E0TL) and synchronous phases (deg).
GAPS = [
    ("GAP_001", 800_000.0, -25.0),
    ("GAP_002", 1_000_000.0, -22.0),
    ("GAP_003", 1_000_000.0, -20.0),
    ("GAP_004", 1_200_000.0, -20.0),
]
SOLENOID_MM = 150.0
SOLENOID_T = 1.5
DRIFT_MM = 150.0
BORE_MM = 20.0          # drift / solenoid / gap aperture radius
COLLIMATOR_MM = 8.0     # APERTURE card radius (~4.4 sigma at 20 MeV)
FOIL_UG_CM2 = 600.0

# Planted solenoid offsets for the orbit-correction check (mm).
PLANTED_DX_MM = {"SOL_001": 0.20, "SOL_002": -0.15, "SOL_003": 0.10}

# PDG 2024 carbon constants (copied from the tables, not from HELIX).
CARBON_X0_G_CM2 = 42.70
CARBON_DEDX_MIN_MEV_CM2_G = 1.745


# --------------------------------------------------------------------------
# Deck
# --------------------------------------------------------------------------
def deck_lines() -> list[str]:
    """The TraceWin-syntax deck (HELIX millimetre convention)."""
    L = []
    L.append("; reliability_demo.dat — generated by make_reliability_demo.py; do not edit by hand")
    L.append(";")
    L.append("; Three cells of (ADJUST_STEERER + THIN_STEERING, SOLENOID, GAP, APERTURE,")
    L.append("; DIAG_POSITION), a fourth GAP, a carbon stripper foil.  Proton 20 MeV,")
    L.append("; 162.5 MHz, 0 mA.  Every element type the reliability legs exercise is")
    L.append("; present; truth.json holds the analytic answers (see the generator).")
    L.append(";")
    L.append("TITLE Reliability demo: 4-gap solenoid channel with orbit correction and a foil")
    L.append(f"FREQ {FREQ_MHZ:g}")
    for cell, (gname, volt, phase) in enumerate(GAPS[:3], start=1):
        L.append(";")
        L.append(f"; -- cell {cell}: {gname} ({volt/1e6:g} MV at {phase:g} deg) -----------------------")
        L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
        L.append(f"ADJUST_STEERER {cell} 0.02 1e-4")
        L.append(f"THIN_STEERING 0.0 0.0 {BORE_MM:g} 0")
        L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
        L.append(f"SOLENOID {SOLENOID_MM:g} {SOLENOID_T:g} {BORE_MM:g}")
        L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
        L.append(f"GAP {volt:g} {phase:g} {BORE_MM:g} 0")
        L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
        L.append(f"APERTURE {COLLIMATOR_MM:g} {COLLIMATOR_MM:g} 1")
        L.append("DIAG_POSITION")
    gname, volt, phase = GAPS[3]
    L.append(";")
    L.append(f"; -- tail: {gname} ({volt/1e6:g} MV at {phase:g} deg), collimator, foil -------------")
    L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
    L.append(f"GAP {volt:g} {phase:g} {BORE_MM:g} 0")
    L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
    L.append(f"APERTURE {COLLIMATOR_MM:g} {COLLIMATOR_MM:g} 1")
    L.append(f"DRIFT {DRIFT_MM:g} {BORE_MM:g}")
    L.append(f"; HELIX_FOIL FOIL_001 C {FOIL_UG_CM2:g} gaussian")   # 23.7 MeV protons sit in the Vavilov regime: pin the Bohr fallback
    L.append(f"DRIFT 100 {BORE_MM:g}")
    L.append("END")
    return L


def sequence() -> list[tuple[str, str, float]]:
    """The clock-relevant element sequence: (kind, name, length_mm).

    Only thick elements advance the RF clock; the gaps are thin.  Names
    follow the parser's auto-labels (``GAP_00n``, ``SOL_00n``).
    """
    seq: list[tuple[str, str, float]] = []
    for cell, (gname, _v, _p) in enumerate(GAPS[:3], start=1):
        seq += [("drift", "", DRIFT_MM), ("drift", "", DRIFT_MM),
                ("solenoid", f"SOL_{cell:03d}", SOLENOID_MM),
                ("drift", "", DRIFT_MM), ("gap", gname, 0.0),
                ("drift", "", DRIFT_MM)]
    seq += [("drift", "", DRIFT_MM), ("gap", GAPS[3][0], 0.0),
            ("drift", "", DRIFT_MM), ("drift", "", DRIFT_MM),
            ("foil", "FOIL_001", 0.0), ("drift", "", 100.0)]
    return seq


# --------------------------------------------------------------------------
# Kinematics (own implementation)
# --------------------------------------------------------------------------
def beta_of(w_mev: float) -> float:
    gamma = 1.0 + w_mev / M_PROTON_MEV
    return math.sqrt(1.0 - 1.0 / (gamma * gamma))


def momentum_mev_c(w_mev: float) -> float:
    return math.sqrt(w_mev * (w_mev + 2.0 * M_PROTON_MEV))


def wrap180(deg: float) -> float:
    return (deg + 180.0) % 360.0 - 180.0


def gap_gain(volt: float, phase_deg: float) -> float:
    """Thin-gap energy gain in MeV: q V T cos(phi), q = 1, T = 1."""
    return volt * 1e-6 * math.cos(math.radians(phase_deg))


def run_chain(off: str | None, frozen: bool, pins: dict[str, float] | None):
    """Walk the sequence; return (W_end, clock phase at each gap entrance,
    dphi seen by each gap, W after each gap)."""
    w = W_INJ_MEV
    phi = 0.0
    entrance: dict[str, float] = {}
    dphi_seen: dict[str, float] = {}
    w_after: dict[str, float] = {}
    volt_of = {g: v for g, v, _p in GAPS}
    phase_of = {g: p for g, _v, p in GAPS}
    for kind, name, length in sequence():
        if length > 0.0:
            phi += 360.0 * length / (beta_of(w) * LAMBDA_MM)
        if kind == "gap":
            entrance[name] = phi
            if name == off:
                dphi_seen[name] = 0.0
                w_after[name] = w
                continue
            dphi = wrap180(phi - pins[name]) if (frozen and pins) else 0.0
            dphi_seen[name] = dphi
            w += gap_gain(volt_of[name], phase_of[name] + dphi)
            w_after[name] = w
    return w, entrance, dphi_seen, w_after


def highland_theta_rad(w_mev: float, x_over_x0: float) -> float:
    p = momentum_mev_c(w_mev)
    beta = beta_of(w_mev)
    return 13.6 / (beta * p) * math.sqrt(x_over_x0) * (1.0 + 0.038 * math.log(x_over_x0))


def truth() -> dict:
    w_nom, pins, _d, w_after_nom = run_chain(None, False, None)
    foil_loss = CARBON_DEDX_MIN_MEV_CM2_G * FOIL_UG_CM2 * 1e-6
    out: dict = {
        "__kind__": "linac_gen_reliability_truth",
        "__version__": 1,
        "constants": {"m_proton_mev": M_PROTON_MEV, "c_light": C_LIGHT,
                      "frequency_mhz": FREQ_MHZ, "lambda_mm": LAMBDA_MM,
                      "w_inj_mev": W_INJ_MEV},
        "nominal": {"w_after_gaps_mev": w_nom,
                    "w_end_envelope_mev": w_nom - foil_loss,
                    "w_end_mp_ref_mev": w_nom,
                    "w_after_gap_mev": w_after_nom,
                    "clock_at_gap_entrance_deg": pins,
                    "note": "the envelope solver decelerates the reference by the foil's "
                            "mean loss; the multiparticle tracker leaves the reference "
                            "untouched (the loss rides on the particles' dw)"},
        "cavity_off_rephased": {},
        "cavity_off_frozen": {},
        "solenoid_off": {"d_energy_mev": 0.0, "note": "exact: a solenoid carries no RF"},
        "ranking": {"top_single_cavity_rephased": None,
                    "k1_compensators_for_GAP_004": ["GAP_003", "GAP_002"],
                    "note": "select_zone(k_out_of_n) takes the 2k nearest same-category "
                            "elements, upstream first on ties"},
        "tolerances": {"energy_rel": 1e-9, "foil_rel": 1e-6},
    }
    worst, worst_d = None, -1.0
    for gname, volt, phase in GAPS:
        d_re = w_nom - run_chain(gname, False, None)[0]
        out["cavity_off_rephased"][gname] = {
            "d_energy_mev": d_re, "formula": f"{volt*1e-6:g} MV * cos({phase:g} deg)"}
        if d_re > worst_d:
            worst, worst_d = gname, d_re
        w_fr, _e, dphi, _wa = run_chain(gname, True, pins)
        out["cavity_off_frozen"][gname] = {
            "d_energy_mev": w_nom - w_fr,
            "dphi_seen_deg": {k: v for k, v in dphi.items() if k != gname}}
    out["ranking"]["top_single_cavity_rephased"] = worst

    x = FOIL_UG_CM2 * 1e-6 / CARBON_X0_G_CM2
    out["foil"] = {
        "element": "FOIL_001", "material": "C", "thickness_ug_cm2": FOIL_UG_CM2,
        "w_at_foil_mev": w_nom,
        "mean_loss_mev": foil_loss,
        "straggling": "gaussian",
        "highland_theta_rms_mrad": 1e3 * highland_theta_rad(w_nom, x),
        "note": "mean loss = PDG minimum-ionising rate x areal density (HELIX's MIP model)",
    }
    a1 = 100.0 / 101.0
    out["availability_closed_forms"] = {
        "single_block": {"mtbf_h": 100.0, "mttr_h": 1.0, "availability": a1},
        "series_two_identical": a1 * a1,
        "parallel_two_identical": 1.0 - (1.0 - a1) ** 2,
        "two_of_three_identical": 3 * a1 ** 2 - 2 * a1 ** 3,
    }
    out["orbit_correction"] = {
        "planted_dx_mm": PLANTED_DX_MM,
        "expect": {"status": "converged", "rms_ratio_max": 1e-2, "transmission_pct": 100.0},
    }
    out["beam"] = {"species": "proton", "energy_mev": W_INJ_MEV, "current_ma": 0.0,
                   "duty_cycle_pct": 1.0}
    return out


def circuits() -> dict:
    return {
        "__kind__": "linac_gen_reliability_circuits",
        "__version__": 1,
        "groups": {
            "cryomodule": {"CM1": ["GAP_001", "GAP_002"], "CM2": ["GAP_003", "GAP_004"]},
            "rf_station": {"RF1": ["GAP_001"], "RF2": ["GAP_002"],
                           "RF3": ["GAP_003"], "RF4": ["GAP_004"]},
            "doublet": {},
            "arc_bus": {},
            "spares": [],
        },
        "sections": [{"name": "LINAC", "end": "GAP_004"},
                     {"name": "TAIL", "end": "FOIL_001"}],
        "treaty_element": "BPM_003",
        "foil_element": "FOIL_001",
    }


def project() -> dict:
    return {
        "__kind__": "linac_gen_project",
        "__version__": 1,
        "lattice_path": "reliability_demo.dat",
        "beam": {
            "species": "proton", "energy": W_INJ_MEV, "frequency": FREQ_MHZ,
            "current": 0.0, "duty_cycle": 1.0, "n_particles": 2000,
            "distribution": "gaussian", "cutoff": 3.0,
            "emit_nx": 0.25, "alpha_x": 0.0, "beta_x": 2.8,
            "emit_ny": 0.25, "alpha_y": 0.0, "beta_y": 2.8,
            "emit_z": 0.1, "alpha_z": 0.0, "beta_z": 100.0,
        },
        "convergence": {},
    }


def main() -> int:
    (_THIS_DIR / "reliability_demo.dat").write_text("\n".join(deck_lines()) + "\n", encoding="utf-8")
    (_THIS_DIR / "reliability_demo.lgproj").write_text(json.dumps(project(), indent=2) + "\n", encoding="utf-8")
    (_THIS_DIR / "circuits.json").write_text(json.dumps(circuits(), indent=2) + "\n", encoding="utf-8")
    t = truth()
    (_THIS_DIR / "truth.json").write_text(json.dumps(t, indent=2) + "\n", encoding="utf-8")
    print(f"wrote reliability_demo.dat ({len(deck_lines())} lines), reliability_demo.lgproj, "
          f"circuits.json, truth.json")
    print(f"  W after the gaps = {t['nominal']['w_after_gaps_mev']:.9f} MeV "
          f"(envelope END {t['nominal']['w_end_envelope_mev']:.9f} after the foil)")
    for g in t["cavity_off_rephased"]:
        print(f"  {g} off: rephased dW = {t['cavity_off_rephased'][g]['d_energy_mev']:.6f}  "
              f"frozen dW = {t['cavity_off_frozen'][g]['d_energy_mev']:.6f} MeV")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
