"""Generate the Hofmann-stability demo linac deck (machine-generic).

A long periodic line — 46 LATTICE-bracketed periods in four sections —
built so the per-section working points land in *different* regions of
the Hofmann chart (R = nu_z/nu_x at zero current, 2.5 MeV proton,
162.5 MHz, phi_s = -90 deg so cells stay strictly periodic in energy):

  A  16 cells  QUAD ±50 T/m, gap 0.10 MV   mu_x=40.2, mu_z=24.9  R0=0.62
  B  12 cells  QUAD ±35 T/m, gap 0.10 MV   mu_x=24.8, mu_z=24.9  R0=1.00
  C  12 cells  QUAD ±29 T/m, gap 0.15 MV   mu_x=13.1, mu_z=30.6  R0=2.34
  D   6 cells  SOLENOID 0.40 T, gap 0.05 MV       (x-y coupled)

Section C sits in the l=3-odd territory of the corrected chart; section
D exists to exercise the coupled-lattice refusal.  Cell geometry:
D30 Q40 D30 GAP D30 Q40 D30 (mm) -> 7 significant elements per period.

Run:  python make_lattice.py      (writes hofmann_demo_linac.dat)
"""
from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).with_name("hofmann_demo_linac.dat")

#: (label, n_cells, quad gradient T/m, gap voltage MV)
QUAD_SECTIONS = [
    ("A", 16, 50.0, 0.10),
    ("B", 12, 35.0, 0.10),
    ("C", 12, 29.0, 0.15),
]
SOLENOID_CELLS = 6
SOLENOID_T = 0.40
SOLENOID_GAP_MV = 0.05
APERTURE = 20.0


def quad_cell(grad: float, volt_mv: float) -> list[str]:
    v = volt_mv * 1e6                       # deck GAP voltage is in volts
    # Positionals per SCHEMA (tracewin_syntax.py): DRIFT L R;
    # QUAD L G R (4th arg is SKEW ANGLE in degrees — never pass steps!);
    # GAP E0TL(V) phase R.
    return [
        f"DRIFT 30.0 {APERTURE}",
        f"QUAD 40.0 {grad:+.1f} {APERTURE}",
        f"DRIFT 30.0 {APERTURE}",
        f"GAP {v:.1f} -90.0 {APERTURE}",
        f"DRIFT 30.0 {APERTURE}",
        f"QUAD 40.0 {-grad:+.1f} {APERTURE}",
        f"DRIFT 30.0 {APERTURE}",
    ]


def solenoid_cell() -> list[str]:
    v = SOLENOID_GAP_MV * 1e6
    return [
        f"DRIFT 30.0 {APERTURE}",
        f"SOLENOID 200.0 {SOLENOID_T} {APERTURE}",
        f"DRIFT 30.0 {APERTURE}",
        f"GAP {v:.1f} -90.0 {APERTURE}",
        f"DRIFT 30.0 {APERTURE}",
    ]


def main() -> None:
    lines = [
        "; Hofmann-stability demo linac — generated by make_lattice.py",
        "; 46 periods in 4 sections; see this directory's README.md",
        "TITLE Hofmann stability demo linac",
        "FREQ 162.5",
    ]
    for label, n_cells, grad, volt in QUAD_SECTIONS:
        lines.append(f"; ---- section {label}: {n_cells} cells, "
                     f"quad {grad:+.0f} T/m, gap {volt:.2f} MV ----")
        lines.append("LATTICE 7 0")
        for _ in range(n_cells):
            lines += quad_cell(grad, volt)
        lines.append("LATTICE_END")
    lines.append(f"; ---- section D: {SOLENOID_CELLS} solenoid cells "
                 "(x-y coupled — exercises the refusal path) ----")
    lines.append("LATTICE 5 0")
    for _ in range(SOLENOID_CELLS):
        lines += solenoid_cell()
    lines.append("LATTICE_END")
    lines.append("END")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
