"""LOCO-style fit: closed loop, Jacobian, scipy anchor, degeneracy, exclusions, cancellation."""
from __future__ import annotations
import numpy as np
import pytest

from linac_gen.core.cancelled import OperationCancelled
from linac_gen.orm import DeviceMap, resolve_devices
from linac_gen.orm.fit import OrmFitOptions, _Problem, _fit_masks, degeneracy_report, fit_orm, run_stages, synthetic_validation
from linac_gen.orm.measured import MeasuredOrm
from linac_gen.orm.model import OrmModel
from tests.orm.conftest import fodo_with_devices
from tests.orm.test_model import _cfg


def _setup(n_cells=6, planes=("x", "y"), seed=0, g_true=None, k_scale=5e-4, G_sigma=0.0, noise_frac=0.01, exclude_bpms=(), fix=()):
    """Synthetic measurement from a perturbed model: returns (measured, model(nominal), truth)."""
    lat = fodo_with_devices(n_cells)
    trims = [f"D{k:02d}T" for k in range(1, n_cells + 1)]; bpms = [f"D{k:02d}{m}BPM" for k in range(1, n_cells + 1) for m in (1, 2)]
    devs_b = {p: [f"L:{b[:-3]}BP{'H' if p == 'x' else 'V'}" for b in bpms] for p in planes}
    devs_t = {p: [f"L:{t}M{'H' if p == 'x' else 'V'}" for t in trims] for p in planes}
    dm = DeviceMap(bpms={d: b for p in planes for d, b in zip(devs_b[p], bpms)}, trims={d: t for p in planes for d, t in zip(devs_t[p], trims)},
                   exclude_bpms=set(exclude_bpms))
    stub = {p: MeasuredOrm(kick_plane=p, trims=devs_t[p], bpms={p: devs_b[p]}, values={p: np.zeros((len(bpms), len(trims)))}, errors={p: np.zeros((len(bpms), len(trims)))}) for p in planes}
    sel = resolve_devices(lat, stub, dm); model = OrmModel(lat, _cfg(), sel)
    rng = np.random.default_rng(seed)
    nq = len(model.quads)
    g = np.ones(nq) if g_true is None else np.asarray(g_true, dtype=float)
    R = model.response(g)
    truth = {"g": g, "k": {}, "G": {}}
    meas = {}
    for p in planes:
        k = -k_scale * rng.uniform(0.6, 1.4, len(trims)); G = 1.0 + rng.normal(0, G_sigma, len(bpms)) if G_sigma else np.ones(len(bpms))
        A = G[:, None] * k[None, :] * R.per_Tm[(p, p)]
        E = noise_frac * np.max(np.abs(A), axis=0)[None, :] * np.ones_like(A) + 1e-9
        A = A + rng.normal(0, 1, A.shape) * E
        meas[p] = MeasuredOrm(kick_plane=p, trims=devs_t[p], bpms={p: devs_b[p]}, values={p: A}, errors={p: E})
        truth["k"][p] = k; truth["G"][p] = G
    sel = resolve_devices(lat, meas, dm); model = OrmModel(lat, _cfg(), sel)
    return meas, model, truth


def test_closed_loop_recovers_quads_and_trims():
    rng = np.random.default_rng(1)
    meas, model, truth = _setup(n_cells=8)
    g_true = 1.0 + rng.normal(0, 0.03, len(model.quads))
    meas, model, truth = _setup(n_cells=8, g_true=g_true, noise_frac=0.01, seed=2)
    fit = fit_orm(model, meas, OrmFitOptions(stage="trims+quads", prior_g=0.10))
    free = ~fit.g_fixed
    assert fit.converged and free.sum() == len(model.quads) - 1                 # the last quad sees one BPM
    assert np.sqrt(np.mean((fit.g - truth["g"])[free] ** 2)) < 0.012          # 3 % injected, 1 % noise
    for p in "xy":
        assert np.nanmax(np.abs(fit.k[p] / truth["k"][p] - 1)) < 0.03
        assert fit.metrics_after[p]["nrms_all"] < 0.5 * fit.metrics_before[p]["nrms_all"]
    assert fit.n_params == free.sum() + 2 * 8 and fit.dof > 0
    assert np.isfinite(fit.g_err[free]).all() and np.median(fit.g_err[free]) < 0.02      # the first quad is weakly determined


def test_closed_loop_with_bpm_gains():
    """With BPM gains free the quads are recovered less sharply (gains and quads trade): 12 cells."""
    rng = np.random.default_rng(4)
    meas, model, truth = _setup(n_cells=12)
    g_true = 1.0 + rng.normal(0, 0.03, len(model.quads))
    meas, model, truth = _setup(n_cells=12, g_true=g_true, G_sigma=0.03, noise_frac=0.01, seed=5)
    fit = fit_orm(model, meas, OrmFitOptions(stage="trims+quads+bpms", prior_g=0.10, prior_G=0.05))
    free = ~fit.g_fixed
    assert fit.converged
    assert np.sqrt(np.mean((fit.g - truth["g"])[free] ** 2)) < 0.02
    for p in "xy":
        assert np.max(np.abs(fit.G[p] - truth["G"][p])) < 0.05                    # within the 5 % prior
        assert fit.metrics_after[p]["nrms_all"] < 0.3 * fit.metrics_before[p]["nrms_all"]
    assert fit.n_params == free.sum() + 2 * 12 + 2 * 24


def test_noise_free_closed_loop():
    """Noise-free data generated by the model itself: the fit reaches the model's own
    precision floor (the bilinear objective has flat, weakly determined directions
    — the first quad is seen through one trim only — so 'exact' means ≈1e-2 in g
    and < 1e-3 of the signal in the residual)."""
    g_true = 1.0 + np.array([0.04, -0.03, 0.02, -0.05, 0.01, 0.0, 0.03, -0.02, 0.0, 0.01, -0.01, 0.02])
    meas, model, truth = _setup(n_cells=6, g_true=g_true, noise_frac=0.0, seed=5)
    fit = fit_orm(model, meas, OrmFitOptions(stage="trims+quads", prior_g=100.0, sys_floor=1e-3, rel_tol=1e-12, max_iter=40))
    free = ~fit.g_fixed
    assert fit.chi2_history[-1] < 1e-3 * fit.chi2_history[0]
    assert np.max(np.abs((fit.g - g_true)[free])) < 2.5e-2 and np.sqrt(np.mean((fit.g - g_true)[free] ** 2)) < 1e-2
    assert fit.metrics_after["x"]["nrms_all"] < 1e-3 and fit.metrics_after["y"]["nrms_all"] < 1e-3
    for p in "xy":
        assert np.nanmax(np.abs(fit.k[p] / truth["k"][p] - 1)) < 5e-3


def test_jacobian_matches_finite_differences():
    meas, model, _ = _setup(n_cells=3, seed=3)
    A, S, masks = _fit_masks(meas, model.sel, 0.05)
    free = np.ones(len(model.quads), dtype=bool); free[-1] = False
    prob = _Problem(model, A, S, masks, OrmFitOptions(stage="trims+quads+bpms", h_g=1e-4), free, True, ("x", "y"))
    rng = np.random.default_rng(0)
    pv = np.concatenate([rng.normal(0, 0.02, prob.nq), rng.uniform(-6e-4, -4e-4, prob.n_k), rng.normal(0, 0.02, prob.n_G)])
    R = model.response(prob.unpack(pv)[0])
    J, r0 = prob.jacobian(pv, R, None)
    for c in range(pv.size):
        h = 1e-6; pq = pv.copy(); pq[c] += h
        Rq = model.response(prob.unpack(pq)[0]) if c < prob.nq else R
        fd = (prob.residuals(pq, Rq) - r0) / h
        assert np.max(np.abs(J[:, c] - fd)) < 1e-4 * max(1.0, np.max(np.abs(fd)))


def test_scipy_trf_reaches_the_same_solution():
    scipy = pytest.importorskip("scipy")
    from scipy.optimize import least_squares
    meas, model, truth = _setup(n_cells=4, g_true=1.0 + np.array([0.03, -0.02, 0.04, -0.01, 0.02, -0.03, 0.01, 0.0]), seed=4)
    opts = OrmFitOptions(stage="trims+quads", rel_tol=1e-10, max_iter=40)
    fit = fit_orm(model, meas, opts)
    A, S, masks = _fit_masks(meas, model.sel, opts.sys_floor)
    prob = _Problem(model, A, S, masks, opts, ~fit.g_fixed, False, ("x", "y"))
    x0 = np.concatenate([np.zeros(prob.nq), fit.k["x"] * 0.8, fit.k["y"] * 0.8])
    res = least_squares(lambda p: prob.residuals(p, model.response(prob.unpack(p)[0])), x0, jac=lambda p: prob.jacobian(p, model.response(prob.unpack(p)[0]), None)[0], method="trf")
    assert abs(2 * res.cost - fit.chi2_history[-1]) < 1e-4 * fit.chi2_history[-1]
    assert np.max(np.abs(1.0 + res.x[:prob.nq] - fit.g[~fit.g_fixed])) < 1e-3


def test_degeneracy_exclusion_and_fixed_quads():
    # the last cell's second quad is followed by a single BPM: held fixed
    meas, model, _ = _setup(n_cells=3, seed=6)
    A, S, masks = _fit_masks(meas, model.sel, 0.05)
    rep = degeneracy_report(model, masks, OrmFitOptions())
    assert set(rep["fixed"]) == {"Q032"} and "only 1 fitted BPM" in rep["fixed"]["Q032"]
    fit = fit_orm(model, meas, OrmFitOptions(stage="trims+quads", fix_quads=("Q011",)))
    assert fit.g_fixed[fit.quads.index("Q011")] and fit.g[fit.quads.index("Q011")] == 1.0 and np.isnan(fit.g_err[fit.quads.index("Q011")])
    assert fit.fixed_reason["Q011"] == "held by the user"
    # excluding the last BPM (both planes) leaves Q031 with one downstream BPM → fixed too
    meas2, model2, _ = _setup(n_cells=3, seed=6, exclude_bpms=("L:D032BPH", "L:D032BPV"))
    fit2 = fit_orm(model2, meas2, OrmFitOptions(stage="trims+quads"))
    assert {"Q031", "Q032"} <= set(fit2.fixed_reason)
    assert fit2.n_data == fit.n_data - 2 * 3                      # one BPM row (3 upstream trims) per plane removed
    with pytest.raises(ValueError, match="unknown quad label"):
        fit_orm(model, meas, OrmFitOptions(stage="trims+quads", fix_quads=("Q99",)))


def test_trims_stage_is_the_closed_form_and_run_stages_chain():
    meas, model, truth = _setup(n_cells=3, seed=7)
    a = fit_orm(model, meas, OrmFitOptions(stage="trims"))
    assert a.converged and a.n_iter == 0 and np.all(a.g == 1.0) and np.isfinite(a.k["x"]).all() and np.isfinite(a.k_err["x"]).all()
    assert np.nanmax(np.abs(a.k["x"] / truth["k"]["x"] - 1)) < 0.05
    res = run_stages(model, meas, OrmFitOptions(stage="trims"))
    assert list(res) == ["trims", "trims+quads", "trims+quads+bpms"] and res["trims+quads+bpms"].stage == "trims+quads+bpms"


def test_cancellation_and_restore():
    meas, model, _ = _setup(n_cells=3, seed=8)
    calls = {"n": 0}

    def stop():
        calls["n"] += 1
        return calls["n"] > 3
    with pytest.raises(OperationCancelled):
        fit_orm(model, meas, OrmFitOptions(stage="trims+quads"), should_stop=stop)
    assert all(q.gradient_rel == 0.0 for q in model.quads)


def test_synthetic_validation_reports():
    meas, model, _ = _setup(n_cells=8, seed=9)
    v = synthetic_validation(model, meas, OrmFitOptions(stage="trims+quads"), seed=3, g_sigma=0.03)
    assert set(v) >= {"g_rms_injected", "g_rms_recovered", "g_max_recovered", "k_rel_rms", "worst_quads", "fit"}
    assert v["g_rms_recovered"] < 0.75 * v["g_rms_injected"] and v["k_rel_rms"] < 0.05
    assert all(q.gradient_rel == 0.0 for q in model.quads)


def test_no_data_refused():
    meas, model, _ = _setup(n_cells=2, seed=1)
    meas["x"].values["x"][:] = np.nan
    with pytest.raises(ValueError, match="no measured entry"):
        fit_orm(model, meas, OrmFitOptions(stage="trims"))
