"""Trust anchors for the corrected Hofmann dispersion solver.

Three independent layers, none of which is a copy of the implementation:

1. **Printed-equation anchors** — the branch functions at the isotropic
   point ``alpha = eta = 1`` must equal Hofmann (1998)'s own published
   isotropic closed forms Eqs. (37)/(42)/(46), transcribed here as
   standalone reference expressions (external ground truth; house rule 3).
2. **Off-isotropic identity pins** — Hofmann's Eq. (24) pairing, the
   p. 4716 emittance identity ``h^2/alpha``, Eq. (5), the gscale
   convention, and the p. 4719 odd-branch interchange, at points where the
   historical coordinate-map defects were visible.  These are the checks
   the iso-limit structurally cannot make (every defect they catch
   vanishes at ``alpha = h = 1``).  Ported from the source manuscript
   package's ``tests/test_hofmann_identities.py``.
3. **Golden cross-repo pins** — 20 chart points spanning both flip
   branches with every branch active somewhere, generated by the source
   package's solver (``PRAB_Hofmann/analysis/dispersion.py``,
   fingerprint 043d0944a1).  On the reference platform (macOS/arm64,
   numpy>=1.24) the HELIX port reproduces them BITWISE; the tolerance
   below allows only last-ulp libm variation on other platforms and any
   failure means the physics drifted from the source package.
"""
from __future__ import annotations

import numpy as np
import pytest

from linac_gen.analysis.hofmann_dispersion import (
    ChartAborted,
    DispersionSolver,
    map_to_pre_grid,
    l3_even_D,
    l3_odd_D,
    l4_even_D,
    l4_odd_D,
)


# =============================================================================
# 1. Printed-equation anchors: iso-limit reduction to Eqs. (37)/(42)/(46)
# =============================================================================

def _D3e_iso_eq37(s, sp2):
    """Hofmann Eq. (37): l=3 even isotropic dispersion function.

    Leading 8; S^2 block 12 S^2/(9-s) (the four Eq. (36) residues collapse
    to (-4+4)/(1-s) + (60+36)/(9-s)); S^4 term -4 S^4 s(3-s) /
    [(9-s)^2 (1-s)^2] (manuscript App. A, Eq. (A6))."""
    return (8.0 + 12.0 * sp2 / (9.0 - s)
            - 4.0 * sp2 ** 2 * s * (3.0 - s)
            / ((9.0 - s) ** 2 * (1.0 - s) ** 2))


def _D4e_iso_eq42(s, sp2):
    """Hofmann Eq. (42): l=4 even isotropic dispersion function, with the
    sp^4-block sign CORRECTED to +34/(16-s)^2 - 2/(4-s)^2.

    The journal prints Eq. (42) with -34/(16-s)^2 + 2/(4-s)^2, which is
    inconsistent with Eq. (41)'s -sp^4; Eq. (43)'s roots (the arbiter,
    ``test_eq43_roots_fix_the_l4_even_sp4_sign``) show Eq. (42) carries
    the typo, so the sign here is flipped from the printed page."""
    g16, g4 = 16.0 - s, 4.0 - s
    return (16.0 + sp2 * (44.0 / g16 - 4.0 / g4)
            + sp2 ** 2 * (34.0 / g16 ** 2 - 2.0 / g4 ** 2)
            + sp2 ** 3 * (6.0 / g16 ** 3 - 2.0 / (g16 * g4 ** 2)
                          + 4.0 / (g16 ** 2 * g4)))


def _D4o_iso_eq46(s, sp2):
    """Hofmann Eq. (46): l=4 odd isotropic dispersion function."""
    g16, g4 = 16.0 - s, 4.0 - s
    return (16.0 + sp2 * (4.0 / g4 + 20.0 / g16)
            + sp2 ** 2 * (4.0 / g16 ** 2 + 4.0 / (g16 * g4)))


@pytest.mark.parametrize("label,D_fn,ref_fn", [
    ("l3_even/Eq37", l3_even_D, _D3e_iso_eq37),
    ("l4_even/Eq42corrected", l4_even_D, _D4e_iso_eq42),
    ("l4_odd/Eq46", l4_odd_D, _D4o_iso_eq46),
])
def test_iso_limit_reduces_to_printed_equations(label, D_fn, ref_fn):
    """At alpha = eta = 1 each branch equals Hofmann's isotropic form to
    machine precision (measured max rel err ~4e-16).  l3_even (Eq. 37) and
    l4_odd (Eq. 46) match the printed page; l4_even matches Eq. (42) with
    the sp^4-block sign corrected per Eq. (43) (see the arbiter test)."""
    rng = np.random.default_rng(0)
    s_vals = -np.exp(rng.uniform(np.log(1e-3), np.log(200.0), 40))
    sp2_vals = rng.uniform(0.1, 5.0, 8)
    for s in s_vals:
        for sp2 in sp2_vals:
            got = D_fn(s, 1.0, 1.0, sp2)
            want = ref_fn(s, sp2)
            assert got == pytest.approx(want, rel=1e-12), (
                f"{label} fails iso reduction at s={s}, sp2={sp2}: "
                f"{got!r} vs printed {want!r}"
            )


def test_l3_odd_equals_even_at_isotropy():
    """The p. 4719 interchange is the identity at alpha = h = 1."""
    for s in (-0.5, -4.0, -20.0):
        for sp2 in (0.5, 2.0, 6.0):
            assert l3_odd_D(s, 1.0, 1.0, sp2) == pytest.approx(
                l3_even_D(s, 1.0, 1.0, sp2), rel=1e-14)


def test_eq43_roots_fix_the_l4_even_sp4_sign():
    """Hofmann Eq. (43)'s closed-form roots settle the Eq. (41)/(42) sign
    conflict (ported from the PRAB_Hofmann reference).

    The journal prints Eq. (41) with -sp^4 AND Eq. (42) with
    -34/(16-s)^2 + 2/(4-s)^2. Those two are mutually inconsistent, so one
    is misprinted. Eq. (43) gives the five closed-form isotropic roots and
    is the independent arbiter: they zero the +34/(16-s)^2 - 2/(4-s)^2 form
    (which factors as -16*prod(s - r_i)) but not the printed one. So
    Eq. (42) carries the typo and Eq. (41)'s printed -sp^4 is correct. An
    earlier version of HELIX adopted +sp^4 because it reduced to the
    *printed* Eq. (42) — validating against the misprinted equation. This
    pins the resolution so the l=4-even sp^4 sign cannot silently revert."""
    sym = pytest.importorskip("sympy")
    s, p = sym.symbols("s p")

    def D42(sign):
        return (16 + p * (sym.Integer(44) / (16 - s) - sym.Integer(4) / (4 - s))
                + p**2 * (sign * 34 / (16 - s)**2 - sign * 2 / (4 - s)**2)
                + p**3 * (6 / (16 - s)**3 - 2 / ((16 - s) * (4 - s)**2)
                          + 4 / ((16 - s)**2 * (4 - s))))

    roots = [16 + p,
             (20 + p + sym.sqrt((20 + p)**2 - 4 * (64 - 2 * p))) / 2,
             (20 + p - sym.sqrt((20 + p)**2 - 4 * (64 - 2 * p))) / 2,
             (40 + p + sym.sqrt((40 + p)**2 - 8 * (128 + 10 * p))) / 4,
             (40 + p - sym.sqrt((40 + p)**2 - 8 * (128 + 10 * p))) / 4]

    # (i) the corrected form is satisfied by every Eq. (43) root; printed is not
    assert all(sym.simplify(sym.together(D42(+1).subs(s, r))) == 0 for r in roots)
    assert not all(sym.simplify(sym.together(D42(-1).subs(s, r))) == 0 for r in roots)

    # (ii) only the corrected form's numerator is exactly the root product (= -16)
    prod = sym.expand(sym.prod([s - r for r in roots]))
    num_ok, _ = sym.fraction(sym.together(D42(+1)))
    q = sym.cancel(sym.expand(num_ok) / prod)
    assert sym.simplify(sym.diff(q, s)) == 0        # s-independent quotient
    assert sym.simplify(q + 16) == 0                # equal to -16

    # (iii) HELIX's l4_even_D (now -sp^4) reduces to the corrected form at iso
    for sv in (-0.3, -2.0, -7.0, -25.0):
        for pv in (0.4, 1.5, 4.0):
            got = float(l4_even_D(sv, 1.0, 1.0, pv))
            want = float(D42(+1).subs({s: sv, p: pv}))
            assert got == pytest.approx(want, rel=1e-12)


# =============================================================================
# 2. Off-isotropic identity pins (port of test_hofmann_identities.py)
# =============================================================================

# (R, eps_ratio) probes spanning both branches of the h >= 1 flip
CASES = [
    (0.88, 1.78), (2.70, 5.00), (1.34, 1.67), (1.50, 1.20),
    (0.50, 3.00), (1.20, 1.68), (2.46, 1.61), (0.97, 1.20),
]


@pytest.mark.parametrize("R,eps", CASES)
def test_emittance_identity_h2_over_alpha(R, eps):
    """Hofmann p.4716: eps_x/eps_y = h^2/alpha, for the plane he calls x.

    Which physical plane is Hofmann's "x" is fixed by h >= 1, so the
    target is eps_z/eps_x when the longitudinal plane carries the larger
    envelope and its reciprocal otherwise."""
    alpha, h, _, _, _ = map_to_pre_grid(np.array([R]), np.array([0.5]), eps)
    alpha, h = alpha.item(), h.item()
    assert h >= 1.0, "Hofmann's h = a/b is defined >= 1 (Eq. 24)"
    flipped = np.sqrt(R / eps) < 1.0
    target = eps if flipped else 1.0 / eps
    assert h * h / alpha == pytest.approx(target, rel=1e-12)


@pytest.mark.parametrize("R,eps", CASES)
@pytest.mark.parametrize("Y", [0.3, 0.55, 0.8, 0.95])
def test_sp2_matches_eq5(R, eps, Y):
    """Eq. (5) inverted: sp2 = (1+h)(1-eta_dep^2)/eta_dep^2 for whichever
    plane Hofmann labels x."""
    alpha, h, sp2, _, _ = map_to_pre_grid(np.array([R]), np.array([Y]), eps)
    h, sp2 = h.item(), sp2.item()
    if np.sqrt(R / eps) >= 1.0:                       # Hofmann-x == transverse
        expect = (1.0 + h) * (1.0 - Y * Y) / (Y * Y)
    else:                                             # Hofmann-x == longitudinal
        expect = (1.0 + h) * (1.0 - Y * Y) / (h * R * R * Y * Y)
    assert sp2 == pytest.approx(expect, rel=1e-12)


@pytest.mark.parametrize("Y", [0.3, 0.6, 0.9])
def test_isotropic_point_unchanged(Y):
    """At R = eps = 1 the map must return the textbook isotropic values."""
    alpha, h, sp2, _, gs = map_to_pre_grid(np.array([1.0]), np.array([Y]), 1.0)
    assert alpha.item() == pytest.approx(1.0, rel=1e-14)
    assert h.item() == pytest.approx(1.0, rel=1e-14)
    assert sp2.item() == pytest.approx(2.0 * (1 - Y * Y) / (Y * Y), rel=1e-12)
    assert gs.item() == pytest.approx(Y, rel=1e-14)


@pytest.mark.parametrize("R,eps", CASES)
@pytest.mark.parametrize("Y", [0.4, 0.75])
def test_gscale_is_active_plane_depression(R, eps, Y):
    """gscale converts sqrt(-s) to Im(omega)/nu_0x for the plane setting s."""
    _, _, _, _, gs = map_to_pre_grid(np.array([R]), np.array([Y]), eps)
    flipped = np.sqrt(R / eps) < 1.0
    assert gs.item() == pytest.approx(R * Y if flipped else Y, rel=1e-12)


@pytest.mark.parametrize("alpha,h,sp2", [
    (0.8, 1.4, 2.0), (1.7, 2.2, 0.7), (0.45, 3.1, 4.5), (2.6, 1.05, 1.3),
])
@pytest.mark.parametrize("s", [-0.5, -3.0, -12.0])
def test_odd_branch_rescales_sp2_and_s(alpha, h, sp2, s):
    """p.4719: the odd interchange acts on Eqs. (24) AND (25) — sp2 and s
    are normalised to nu_x^2, so the interchange rescales both.  Holding
    sp2 or s fixed is the historical defect this pins."""
    got = l3_odd_D(s, alpha, h, sp2)
    want = l3_even_D(s / alpha ** 2, 1.0 / alpha, 1.0 / h, sp2 / alpha ** 2)
    assert got == pytest.approx(want, rel=1e-12)


@pytest.mark.parametrize("eps,Y", [
    (5.0, 0.35), (5.0, 0.30), (3.0, 0.40), (8.5, 0.30), (1.5, 0.45),
])
def test_physical_growth_continuous_across_seam(eps, Y):
    """gamma/nu_0x must be continuous across the h = 1 interchange
    boundary: the internal variables jump by the relabelling factors, but
    the observable growth rate is invariant."""
    s = DispersionSolver()
    lo = s.growth_rate(R=eps - 1e-6, Y=Y, eps_ratio=eps, l_modes=(2, 3, 4))
    hi = s.growth_rate(R=eps + 1e-6, Y=Y, eps_ratio=eps, l_modes=(2, 3, 4))
    scale = max(lo, hi)
    if scale < 1e-3:
        pytest.skip("no resolved growth at this seam point")
    assert abs(hi - lo) / scale < 1e-5


def test_seam_internal_variables_jump_by_the_relabelling_factors():
    """Pin HOW the internal variables jump at h = 1, so the relabelling
    stays explicit rather than looking like a broken map."""
    eps, Y = 1.5, 0.5
    a_lo, h_lo, sp2_lo, _, gs_lo = map_to_pre_grid(
        np.array([eps - 1e-6]), np.array([Y]), eps)
    a_hi, h_hi, sp2_hi, _, gs_hi = map_to_pre_grid(
        np.array([eps + 1e-6]), np.array([Y]), eps)
    R = eps
    assert h_lo.item() == pytest.approx(1.0, abs=1e-5)
    assert h_hi.item() == pytest.approx(1.0, abs=1e-5)
    assert a_lo.item() == pytest.approx(1.0 / R, rel=1e-5)     # flipped frame
    assert a_hi.item() == pytest.approx(R, rel=1e-5)           # unflipped
    assert sp2_lo.item() / sp2_hi.item() == pytest.approx(1.0 / R ** 2,
                                                          rel=1e-5)
    assert gs_lo.item() / gs_hi.item() == pytest.approx(R, rel=1e-5)


# =============================================================================
# 3. Golden cross-repo pins (source-package solver, fingerprint 043d0944a1)
# =============================================================================

# Each row: R, Y, eps, alpha, eta, sp2, gscale, g_l2, raw_l3_even,
# raw_l3_odd, raw_l4_even, raw_l4_odd, g_all — printed by the source
# package at repr() precision (round-trips exactly).  Regenerate with the
# same triples through PRAB_Hofmann/analysis/dispersion.py if the source
# physics ever changes intentionally.
GOLDEN_PINS = [
    (1.0, 0.5, 1.0, 1.0, 1.0, 6.0, 0.5,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (1.0, 0.9, 1.0, 1.0, 1.0, 0.46913580246913567, 0.9,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (1.0, 0.2, 1.0, 1.0, 1.0, 47.999999999999986, 0.2,
     0.0, 0.0, 0.0, 0.683648944435791, 0.0, 0.13672978888715823),
    (1.5, 0.5, 1.0, 1.5, 1.224744871391589, 6.674234614174766, 0.5,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (2.0, 0.3, 1.2, 2.0, 1.2909944487358056, 23.164499426106477, 0.3,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (2.8, 0.6, 1.5, 2.8, 1.3662601021279464, 4.206684626005239, 0.6,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.6, 0.5, 1.0, 1.6666666666666667, 1.2909944487358056, 14.788305577012363, 0.3,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.5, 0.4, 1.8, 2.0, 1.8973665961010275, 32.06797181058932, 0.2,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.9, 0.7, 2.5, 1.1111111111111112, 1.6666666666666667, 2.055933484504913, 0.63,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (1.2, 0.45, 5.0, 0.8333333333333334, 2.041241452319315, 4.074738045178041, 0.54,
     0.13023773916271922, 0.0, 0.0, 0.2170273395074025, 0.0, 0.13023773916271922),
    (1.5, 0.5, 1.5, 1.5, 1.0, 6.0, 0.5,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.88, 0.55, 1.78, 1.1363636363636365, 1.4222261679238195, 5.071068945487758, 0.48400000000000004,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (1.44, 0.62, 1.67, 0.6944444444444444, 1.076903998610007, 1.489462868341015, 0.8927999999999999,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (1.08, 0.83, 1.17, 0.9259259259259258, 1.0408329997330663, 0.7591414941990378, 0.8964,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (2.7, 0.3, 5.0, 0.37037037037037035, 1.3608276348795434, 2.406204389239152, 0.81,
     0.0, 0.29263192139860533, 0.2140093320804818, 0.0, 0.0, 0.23703185633287033),
    (0.35, 0.25, 1.3, 2.857142857142857, 1.927248223318863, 185.98463530564544, 0.0875,
     0.0, 0.5260152200877216, 1.0673532888950241, 0.9500009600147544, 0.0, 0.0933934127783146),
    (0.811, 0.443, 0.58, 0.811, 1.1824871509107258, 8.938523151871586, 0.443,
     0.058938344390146925, 0.0, 0.0, 0.18326946949141443, 0.0, 0.0811883749846966),
    (1.835, 0.197, 2.877, 0.5449591280653951, 1.2521371376347488, 13.229640462580972, 0.361495,
     0.08743661105884878, 0.0, 0.43019523197700343, 0.7229112172509597, 0.0, 0.2613287904801357),
    (0.368, 0.464, 5.747, 2.717391304347826, 3.951815763176082, 33.72423110118122, 0.17075200000000001,
     0.0, 0.0, 0.0, 0.0, 0.19031549988992444, 0.0),
    (0.358, 0.572, 4.689, 2.793296089385475, 3.619083497672925, 20.47837114181039, 0.20477599999999999,
     0.0, 0.0, 0.0, 0.0, 0.06857450920626008, 0.0),
]

# Bitwise on the reference platform; rel=1e-12 admits only last-ulp libm
# variation elsewhere.  Root-scan outputs get abs=1e-12 as well because
# the bisection resolves roots to ~1e-13 absolute.
_PIN_REL, _PIN_ABS = 1e-12, 1e-12


@pytest.mark.parametrize("pin", GOLDEN_PINS,
                         ids=[f"R{p[0]}_Y{p[1]}_e{p[2]}" for p in GOLDEN_PINS])
def test_golden_pin_map(pin):
    R, Y, eps, alpha_e, eta_e, sp2_e, gs_e = pin[:7]
    a, e, sp2, _, gs = map_to_pre_grid(np.array([R]), np.array([Y]), eps)
    assert a.item() == pytest.approx(alpha_e, rel=1e-14)
    assert e.item() == pytest.approx(eta_e, rel=1e-14)
    assert sp2.item() == pytest.approx(sp2_e, rel=1e-14)
    assert gs.item() == pytest.approx(gs_e, rel=1e-14)


@pytest.mark.parametrize("pin", GOLDEN_PINS,
                         ids=[f"R{p[0]}_Y{p[1]}_e{p[2]}" for p in GOLDEN_PINS])
def test_golden_pin_growth(pin):
    R, Y, eps = pin[:3]
    g_l2_e, l3e_e, l3o_e, l4e_e, l4o_e, g_all_e = pin[7:]
    s = DispersionSolver()
    a, e, sp2, _, _ = map_to_pre_grid(np.array([R]), np.array([Y]), eps)
    a, e, sp2 = a.item(), e.item(), sp2.item()
    assert s.growth_rate(R=R, Y=Y, eps_ratio=eps, l_modes=(2,)) == \
        pytest.approx(g_l2_e, rel=_PIN_REL, abs=_PIN_ABS)
    for branch, exp in (("l3_even", l3e_e), ("l3_odd", l3o_e),
                        ("l4_even", l4e_e), ("l4_odd", l4o_e)):
        assert s.solve_branch_raw(branch, a, e, sp2) == \
            pytest.approx(exp, rel=_PIN_REL, abs=_PIN_ABS), branch
    assert s.growth_rate(R=R, Y=Y, eps_ratio=eps, l_modes=(2, 3, 4)) == \
        pytest.approx(g_all_e, rel=_PIN_REL, abs=_PIN_ABS)


# =============================================================================
# 4. Regression pins ported from the source package (test_dispersion_new.py)
# =============================================================================

@pytest.fixture(scope="module")
def solver():
    return DispersionSolver()


def _aesp(R, Y, eps):
    a, e, sp2, _, gs = map_to_pre_grid(np.array([R]), np.array([Y]), eps)
    return a.item(), e.item(), sp2.item(), gs.item()


def test_l2_stable_above_unity(solver):
    assert solver.growth_rate(R=1.0, Y=1.0, eps_ratio=1.0, l_modes=(2,)) == 0.0


def test_l2_peak_eps573(solver):
    """l=2 growth at an in-domain (sp^2 = 9.1) anisotropic point; the
    signal comes from the ODD (tilting) branch."""
    g = solver.growth_rate(R=1.10, Y=0.34, eps_ratio=5.73, l_modes=(2,))
    assert g == pytest.approx(0.095687, abs=5e-4)


BRANCH_PINS = [
    # branch, R, Y, eps, raw, scaled, tol — source-package regression pins
    ("l3_even", 2.10, 0.30, 5.73, 0.183286, 0.115470, 5e-4),   # sp^2 = 3.68
    ("l3_odd",  1.30, 0.32, 2.00, 0.095025, 0.039530, 5e-4),   # sp^2 = 9.37
    ("l4_even", 1.10, 0.40, 8.50, 0.330861, 0.145579, 5e-4),   # sp^2 = 5.90 (-sp^4)
    ("l3_odd",  2.10, 0.30, 5.73, 0.294567, 0.185577, 5e-4),   # sp^2 = 3.68
    ("l4_even", 2.10, 0.30, 5.73, 0.048116, 0.030313, 5e-4),   # -sp^4: now active
    ("l4_odd",  1.10, 0.40, 8.50, 0.000000, 0.000000, 1e-6),   # quiet
]


@pytest.mark.parametrize("branch,R,Y,eps,raw_exp,scaled_exp,tol", BRANCH_PINS)
def test_branch_pin(solver, branch, R, Y, eps, raw_exp, scaled_exp, tol):
    a, e, sp2, gs = _aesp(R, Y, eps)
    raw = solver.solve_branch_raw(branch, a, e, sp2)
    assert raw == pytest.approx(raw_exp, abs=tol)
    assert raw * gs == pytest.approx(scaled_exp, abs=tol)


@pytest.mark.parametrize("R,Y,expected,tol", [
    (2.10, 0.30, 0.185577, 5e-4),  # in-domain, l=3 odd sets it
    (0.60, 0.46, 0.125210, 5e-4),  # out of domain (regression only)
    (0.80, 0.30, 0.206709, 5e-4),  # out of domain (regression only)
])
def test_aggregate_l23(solver, R, Y, expected, tol):
    g = solver.growth_rate(R=R, Y=Y, eps_ratio=5.73, l_modes=(2, 3))
    assert g == pytest.approx(expected, abs=tol)


@pytest.mark.parametrize("R,Y,expected,tol", [
    (1.50, 0.25, 0.278502, 5e-4),  # at the domain edge (-sp^4)
    (0.60, 0.59, 0.069042, 5e-4),  # in-domain
    (0.60, 0.46, 0.125210, 5e-4),  # out of domain (regression only)
])
def test_aggregate_l234(solver, R, Y, expected, tol):
    g = solver.growth_rate(R=R, Y=Y, eps_ratio=5.73, l_modes=(2, 3, 4))
    assert g == pytest.approx(expected, abs=tol)


# =============================================================================
# 5. Structural sanity + HELIX-added hooks
# =============================================================================

def test_grid_refinement_stability(solver):
    D_fn = solver.l3_even_dispersion(alpha=0.5, eta=2.0, sp2=1.5)
    g_default = solver._find_growth_rate_func(D_fn, n_scan=2000)
    g_refined = solver._find_growth_rate_func(D_fn, n_scan=8000)
    if g_default > 1e-6:
        assert g_refined == pytest.approx(g_default, rel=0.01)
    else:
        assert g_refined < 1e-3


def test_unknown_branch_raises(solver):
    with pytest.raises(KeyError):
        solver.solve_branch_raw("l5_even", 1.0, 1.0, 1.0)


def test_batch_matches_scalar(solver):
    """growth_rate_batch == a growth_rate loop (the per-row scan grids
    differ from the scalar path by last-ulp rounding only)."""
    rng = np.random.default_rng(3)
    R = rng.uniform(0.1, 3.0, 50)
    Y = rng.uniform(0.15, 0.95, 50)
    for eps in (1.0, 1.475, 5.73):
        g_batch = solver.growth_rate_batch(R, Y, eps)
        g_scalar = np.array([
            solver.growth_rate(R=float(r), Y=float(y), eps_ratio=eps)
            for r, y in zip(R, Y)
        ])
        np.testing.assert_allclose(g_batch, g_scalar, rtol=1e-9, atol=1e-9)


def test_chart_should_stop_aborts(solver):
    with pytest.raises(ChartAborted):
        solver.chart(1.475, steps=100, should_stop=lambda: True)


def test_chart_progress_reports_chunks(solver):
    calls: list = []
    r, y, G = solver.chart(1.475, steps=100, l_modes=(2,),
                           progress=lambda i, n: calls.append((i, n)))
    assert G.shape == (y.size, r.size)
    assert calls, "progress was never called"
    assert calls[-1][0] == calls[-1][1]        # final chunk == n_chunks
    assert [c[0] for c in calls] == list(range(1, len(calls) + 1))
